In [25]:
!pip install pandas

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: pandas in /home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages (0.24.2)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages (from pandas) (2.8.0)
Requirement already satisfied: pytz>=2011k in /home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages (from pandas) (2019.3)
Requirement already satisfied: numpy>=1.12.0 in /home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages (from pandas) (1.16.5)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)

In [26]:
import pandas as pd

In [27]:
# Import the datasets 
us_daily_df = pd.read_csv("https://github.com/COVID19Tracking/covid-tracking-data/raw/master/data/us_daily.csv")
us_current_df = pd.read_csv("https://github.com/COVID19Tracking/covid-tracking-data/raw/master/data/us_current.csv")
cdc_deaths_by_state_df = pd.read_csv("https://raw.githubusercontent.com/COVID19Tracking/covid-tracking-data/master/data/cdc_cases_deaths.csv")

In [28]:
## UNDERSTAND DATA STRUCTURE

In [30]:
# Print the dataframe structure for US Daily COVID-19
print(us_daily_df.columns)

Index([u'date', u'states', u'positive', u'negative', u'pending',
       u'hospitalizedCurrently', u'hospitalizedCumulative', u'inIcuCurrently',
       u'inIcuCumulative', u'onVentilatorCurrently', u'onVentilatorCumulative',
       u'dateChecked', u'death', u'hospitalized', u'totalTestResults',
       u'lastModified', u'recovered', u'total', u'posNeg', u'deathIncrease',
       u'hospitalizedIncrease', u'negativeIncrease', u'positiveIncrease',
       u'totalTestResultsIncrease', u'hash'],
      dtype='object')

In [31]:
# Print the dataframe structure for US Current COVID-19
print(us_current_df.columns)

Index([u'date', u'states', u'positive', u'negative', u'pending',
       u'hospitalizedCurrently', u'hospitalizedCumulative', u'inIcuCurrently',
       u'inIcuCumulative', u'onVentilatorCurrently', u'onVentilatorCumulative',
       u'dateChecked', u'death', u'hospitalized', u'totalTestResults',
       u'lastModified', u'recovered', u'total', u'posNeg', u'deathIncrease',
       u'hospitalizedIncrease', u'negativeIncrease', u'positiveIncrease',
       u'totalTestResultsIncrease', u'hash'],
      dtype='object')

In [32]:
# Print the dataframe structure for CDC's Death by States from COVID-19 Dataset
print(cdc_deaths_by_state_df.columns)

Index([u'submission_date', u'state', u'tot_cases', u'conf_cases',
       u'prob_cases', u'new_case', u'pnew_case', u'tot_death', u'conf_death',
       u'prob_death', u'new_death', u'pnew_death', u'created_at',
       u'consent_cases', u'consent_deaths'],
      dtype='object')

In [33]:
## PROCESS DATAFRAMES AND HANDLE DATA PREPARATION

In [34]:
us_daily_df['date'] = pd.to_datetime(us_daily_df['date'], infer_datetime_format=True)
us_current_df['date'] = pd.to_datetime(us_current_df['date'], infer_datetime_format=True)
cdc_deaths_by_state_df['submission_date'] = pd.to_datetime(cdc_deaths_by_state_df['submission_date'], infer_datetime_format=True)

us_daily_df['month'] = us_daily_df['date'].dt.month
us_current_df['month'] = us_current_df['date'].dt.month
cdc_deaths_by_state_df['submission_date_month'] = cdc_deaths_by_state_df['submission_date'].dt.month

us_daily_df = us_daily_df.fillna(0)
us_current_df = us_current_df.fillna(0)
cdc_deaths_by_state_df = cdc_deaths_by_state_df.fillna(0)

In [35]:
## UNDERSTAND SAMPLE DATA ENTRIES (CATEGORICAL/QUANTITATIVE)

In [36]:
# Print the first 5 entries of the US Daily COVID-19 dataset
print(us_daily_df.head(5))

                           date  states    positive    negative  pending  \
0 1970-01-01 00:00:00.020210307      56  28756489.0  74582825.0  11808.0
1 1970-01-01 00:00:00.020210306      56  28714654.0  74450990.0  11783.0
2 1970-01-01 00:00:00.020210305      56  28654639.0  74307155.0  12213.0
3 1970-01-01 00:00:00.020210304      56  28585852.0  74035238.0  12405.0
4 1970-01-01 00:00:00.020210303      56  28520365.0  73857281.0  11778.0

   hospitalizedCurrently  hospitalizedCumulative  inIcuCurrently  \
0                40199.0                776361.0          8134.0
1                41401.0                775635.0          8409.0
2                42541.0                775132.0          8634.0
3                44172.0                772351.0          8970.0
4                45462.0                770821.0          9359.0

   inIcuCumulative  onVentilatorCurrently  ...  recovered total  posNeg  \
0          45475.0                 2802.0  ...        0.0     0       0
1          45453.0                 2811.0  ...        0.0     0       0
2          45373.0                 2889.0  ...        0.0     0       0
3          45293.0                 2973.0  ...        0.0     0       0
4          45214.0                 3094.0  ...        0.0     0       0

   deathIncrease  hospitalizedIncrease negativeIncrease  positiveIncrease  \
0            842                   726           131835             41835
1           1680                   503           143835             60015
2           2221                  2781           271917             68787
3           1743                  1530           177957             65487
4           2449                  2172           267001             66836

   totalTestResultsIncrease                                      hash  month
0                   1170059  a80d0063822e251249fd9a44730c49cb23defd83      1
1                   1430992  dae5e558c24adb86686bbd58c08cce5f610b8bb0      1
2                   1744417  724844c01659d0103801c57c0f72bf8cc8ab025c      1
3                   1590984  5c549ad30f9abf48dc5de36d20fa707014be1ff3      1
4                   1406795  fef6c425d2b773a9221fe353f13852f3e4a4bfb0      1

[5 rows x 26 columns]

In [37]:
# Print the first entry of the US Current COVID-19 dataset (This is the latest data entry)
print(us_current_df.head(1))

                           date  states  positive  negative  pending  \
0 1970-01-01 00:00:00.020210307      56  28756489  74582825    11808

   hospitalizedCurrently  hospitalizedCumulative  inIcuCurrently  \
0                  40199                  776361            8134

   inIcuCumulative  onVentilatorCurrently  ...  recovered total  posNeg  \
0            45475                   2802  ...        0.0     0       0

   deathIncrease  hospitalizedIncrease negativeIncrease  positiveIncrease  \
0            842                   726           131835             41835

   totalTestResultsIncrease                                      hash  month
0                   1170059  a80d0063822e251249fd9a44730c49cb23defd83      1

[1 rows x 26 columns]

In [38]:
# Print the first 5 entries of the CDC's Deaths By States COVID-19 dataset (This is the latest data entry)
print(cdc_deaths_by_state_df.head(5))

  submission_date state  tot_cases  conf_cases  prob_cases  new_case  \
0      2021-12-01    ND     163565    135705.0     27860.0       589
1      2021-05-06    WA     409847         0.0         0.0      1516
2      2021-09-01    ND     118491    107475.0     11016.0       536
3      2021-07-20    MD     464491         0.0         0.0       155
4      2020-05-13    VT        855         0.0         0.0         2

   pnew_case  tot_death  conf_death  prob_death  new_death  pnew_death  \
0      220.0       1907         0.0         0.0          9         0.0
1      286.0       5553         0.0         0.0         14         0.0
2       66.0       1562         0.0         0.0          1         0.0
3        0.0       9822      9604.0       218.0          3         1.0
4        0.0         52         0.0         0.0          0         0.0

               created_at consent_cases consent_deaths  submission_date_month
0  12/02/2021 02:35:20 PM         Agree      Not agree                     12
1  05/08/2021 12:00:00 AM             0              0                      5
2  09/02/2021 01:49:05 PM         Agree      Not agree                      9
3  07/22/2021 12:00:00 AM             0          Agree                      7
4  05/15/2020 12:00:00 AM     Not agree      Not agree                      5

In [39]:
## DESCRIBE THE DATASET STATISTICS (COUNTS, MEANS, STD DEVIATIONS, MINS, MAXS, ETC.)

In [40]:
# Describe the US Daily dataset (No need to describe the US Current since there is only 1 entry)
us_daily_df.describe()

,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,onVentilatorCumulative,...,totalTestResults,recovered,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,month
count,420.000000,4.200000e+02,4.200000e+02,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,420.000000,...,4.200000e+02,420.0,420.0,420.0,420.000000,420.000000,420.000000,420.000000,4.200000e+02,420.0
mean,49.476190,8.097361e+06,2.684030e+07,8449.492857,49150.985714,273075.059524,9963.219048,17449.171429,3293.819048,1765.026190,...,1.073369e+08,0.0,0.0,0.0,1226.550000,1848.478571,177578.154762,68467.830952,8.662503e+05,1.0
std,16.896764,8.965476e+06,2.462763e+07,9815.050413,36019.975299,243032.259777,6889.541077,14686.934620,2495.174988,1467.368649,...,1.129172e+08,0.0,0.0,0.0,1070.129644,1708.460481,121479.721129,68682.221496,6.579463e+05,0.0
min,1.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.0,0.0,0.0,0.000000,-2858.000000,-658774.000000,0.000000,0.000000e+00,1.0
25%,56.000000,9.861690e+05,2.049857e+06,2417.000000,30033.000000,40260.250000,6300.250000,3432.750000,1630.750000,245.750000,...,5.888598e+06,0.0,0.0,0.0,439.750000,765.750000,79236.750000,22462.500000,2.388558e+05,1.0
50%,56.000000,5.023652e+06,2.218214e+07,8563.500000,43463.000000,237924.000000,9134.000000,15119.500000,2634.500000,1585.000000,...,6.839699e+07,0.0,0.0,0.0,1016.000000,1490.000000,206620.000000,44664.500000,8.223685e+05,1.0
75%,56.000000,1.230270e+07,4.803752e+07,11735.250000,59796.500000,431210.750000,14260.500000,28868.500000,5260.000000,3097.000000,...,1.854937e+08,0.0,0.0,0.0,1642.500000,2467.000000,260621.000000,89684.250000,1.401706e+06,1.0
max,56.000000,2.875649e+07,7.458282e+07,65698.000000,132474.000000,776361.000000,23912.000000,45475.000000,8004.000000,4281.000000,...,3.638251e+08,0.0,0.0,0.0,5427.000000,17155.000000,480256.000000,295121.000000,2.309884e+06,1.0

In [41]:
# Describe the CDC's Deaths by State dataset (No need to describe the US Current since there is only 1 entry)
cdc_deaths_by_state_df.describe()

,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,submission_date_month
count,4.902000e+04,4.902000e+04,49020.000000,49020.000000,49020.000000,49020.000000,49020.000000,49020.00000,49020.000000,49020.000000,49020.000000
mean,4.693775e+05,2.664543e+05,39061.208364,1631.223460,241.090269,7608.039922,4249.313525,474.11020,19.778213,1.876316,6.111383
std,8.607875e+05,6.382039e+05,89618.172365,5264.594377,1490.604155,12364.865265,8171.687583,1051.08653,47.039227,26.207609,3.486478
min,0.000000e+00,0.000000e+00,0.000000,-10199.000000,-171804.000000,0.000000,0.000000,0.00000,-352.000000,-2594.000000,1.000000
25%,9.213250e+03,0.000000e+00,0.000000,24.000000,0.000000,193.000000,0.000000,0.00000,0.000000,0.000000,3.000000
50%,1.445015e+05,2.665000e+02,0.000000,372.000000,0.000000,2386.000000,2.000000,0.00000,4.000000,0.000000,6.000000
75%,5.819702e+05,2.657920e+05,24932.500000,1409.000000,142.000000,9648.500000,5366.000000,314.25000,19.000000,0.000000,9.000000
max,9.140562e+06,8.535899e+06,606418.000000,319809.000000,171617.000000,88907.000000,71408.000000,6893.00000,1178.000000,2919.000000,12.000000